name: coverage

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    name: Coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-7.4-illuminate-7.*-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: xdebug

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-suggest

      - name: Calculate coverage statistics
        run: phpunit --coverage-clover 'clover.xml'

      - name: Send coverage statistics
        uses: codecov/codecov-action@v1
